### PR TITLE
Fix errors with Goodtables2

### LINKED ISSUE #25: Report expects "row-number" key
# Overview

Hi,
I'm trying to use the UI to show a simple report of a repeated column name. The report is as follows:
```
{
          "error-count": 1,
          "preset": "table",
          "table-count": 1,
          "tables": [
            {
              "encoding": "utf-8",
              "error-count": 1,
              "errors": [
                {
                  "code": "duplicate-header",
                  "column-number": 5,
                  "message": "Header in column 5 is duplicated to header in column(s) 4",
                  "message-data": {
                    "column_numbers": "4",
                    "original": "4"
                  }
                }
              ],
              "format": "csv",
              "headers": [
                "col1",
                "col2",
                "col3",
                "col4",
                "col4"
              ],
              "row-count": 5,
              "schema": "table-schema",
              "scheme": "s3",
              "source": "s3://submissions/testing5/files/test2.csv",
              "time": 0.079,
              "valid": false
            }
          ],
          "time": 0.102,
          "valid": false,
          "warnings": null
        }
},
```
The line here https://github.com/frictionlessdata/goodtables-ui/blob/master/src/helpers.js#L51 assumes that there is a 'row-number' key in the error dict. Because there isn't, the resulting structure looks something like:
Screenshot from 2020-01-13 11-25-50
As you can see, the rows key has undefined as a value in the dictionary. Down the line this ends up leading to an error in ErrorGroupTable here https://github.com/frictionlessdata/goodtables-ui/blob/master/src/components/ErrorGroup.js#L113
`TypeError: errorGroup.rows[rowNumber] is undefined`

I think at some point the undefined value is converted into a null value and then it leads to this error.

---

Please preserve this line to notify @roll (lead of this repository)

### PR DESCRIPTION
**Pull request by roll**
- fixes #25

### CODE REVIEW

**Comment by cschloer** [comment]
This isn't working for the report:

```
"validationReport": {
          "error-count": 7,
          "preset": "table",
          "table-count": 1,
          "tables": [
            {
              "encoding": null,
              "error-count": 7,
              "errors": [
                {
                  "code": "schema-error",
                  "column-number": null,
                  "message": "Table Schema error: Descriptor validation error: {'name': None, 'type': 'integer', 'format': 'default'} is not valid under any of the given schemas at \"fields/1\" in descriptor and at \"properties/fields/items/anyOf\" in profile",
                  "row": null,
                  "row-number": null
                },
                {
                  "code": "schema-error",
                  "column-number": null,
                  "message": "Table Schema error: Descriptor validation error: {'name': None, 'type': 'number', 'format': 'default'} is not valid under any of the given schemas at \"fields/2\" in descriptor and at \"properties/fields/items/anyOf\" in profile",
                  "row": null,
                  "row-number": null
                },
                {
                  "code": "schema-error",
                  "column-number": null,
                  "message": "Table Schema error: Descriptor validation error: {'name': None, 'type': 'number', 'format': 'default'} is not valid under any of the given schemas at \"fields/3\" in descriptor and at \"properties/fields/items/anyOf\" in profile",
                  "row": null,
                  "row-number": null
                },
                {
                  "code": "schema-error",
                  "column-number": null,
                  "message": "Table Schema error: Descriptor validation error: {'name': None, 'type': 'string', 'format': 'default'} is not valid under any of the given schemas at \"fields/4\" in descriptor and at \"properties/fields/items/anyOf\" in profile",
                  "row": null,
                  "row-number": null
                },
                {
                  "code": "schema-error",
                  "column-number": null,
                  "message": "Table Schema error: Descriptor validation error: {'name': None, 'type': 'string', 'format': 'default'} is not valid under any of the given schemas at \"fields/5\" in descriptor and at \"properties/fields/items/anyOf\" in profile",
                  "row": null,
                  "row-number": null
                },
                {
                  "code": "schema-error",
                  "column-number": null,
                  "message": "Table Schema error: Descriptor validation error: {'name': None, 'type': 'any', 'format': 'default'} is not valid under any of the given schemas at \"fields/6\" in descriptor and at \"properties/fields/items/anyOf\" in profile",
                  "row": null,
                  "row-number": null
                },
                {
                  "code": "schema-error",
                  "column-number": null,
                  "message": "Table Schema error: Descriptor validation error: {'name': None, 'type': 'any', 'format': 'default'} is not valid under any of the given schemas at \"fields/7\" in descriptor and at \"properties/fields/items/anyOf\" in profile",
                  "row": null,
                  "row-number": null
                }
              ],
              "format": "xlsx",
              "headers": null,
              "row-count": 0,
              "schema": "table-schema",
              "scheme": "s3",
              "source": "s3://submissions/test1/files/substrate.xlsx",
              "time": 0.092,
              "valid": false
            }
          ],
          "time": 0.093,
          "valid": false,
          "warnings": null
        }
```

The error is: `TypeError: t.rows[e].values is null`

**Comment by cschloer** [comment]
Also, if you are considering a (breaking?) update to v2 of goodtables, would you also consider upgrading the dependency to Bootstrap 2.0? Goodtables-ui is still using an alpha version of Bootstrap and I ran into some problems with conflicting dependencies (though I was able to get around them so it's not a big deal).

**Comment by roll** [comment]
I've created an issue - https://github.com/frictionlessdata/goodtables-ui/issues/28

**Comment by roll** [comment]
@cschloer 
Thanks. I've made it not failing.

I'm trying to fix all blockers now but the component clearly needs some refreshment. I will improve it during the pilot

**Comment by cschloer** [comment]
Works now as far as I can tell :+1:

**Comment by roll** [comment]
Thanks!

**Pull request merged**
