### PR TITLE
Redesigned Report UI

### PR DESCRIPTION
**Pull request by roll**

### CODE REVIEW

**Comment by roll** [comment]
@smth 
@amercader 
Could you please review?

I've merged to focus on visual testing:
- https://frictionlessdata.github.io/goodtables-ui/?source=https%3A%2F%2Fraw.githubusercontent.com%2Ffrictionlessdata%2Fgoodtables-py%2Fmaster%2Fdata%2Finvalid.csv&apiJobId=65f8890f-9db5-4e45-a582-dd8cf89b98b9

**Comment by roll** [comment]
One problem I see that some horizontal lines break out of the container. It seems OK for the goodtables.io design http://p.smth.uk/goodtables/jobs/report/ but could be a problem for other users.

**Comment by amercader** [comment]
Nice one.

* I'm seeing these rounded corners on the highlighted error row

2018-01-23-16-32-frictionlessdata github io
2018-01-23-16-31-frictionlessdata github io

* Are these horizontal line popping out meant to be there?
2018-01-23-16-33-frictionlessdata github io.
**edit**: ah, saw your comment above. Not sure how this is going to look like in other apps.

* We need some sort of horizontal scrolling for large tables, otherwise you can't see all errors/fields:
https://frictionlessdata.github.io/goodtables-ui/?source=https%3A%2F%2Fgithub.com%2Famercader%2Fcar-fuel-and-emissions%2Fraw%2Fmaster%2Fdata.csv&schema=https%3A%2F%2Fgithub.com%2Famercader%2Fcar-fuel-and-emissions%2Fraw%2Fmaster%2Fschema.json&apiJobId=50e5dc4d-8094-4027-8154-d6b2c2aa3d37

* I wouldn't display warnings as "buttons"


A good test would be to update ckanext-validation or any of the others apps that reuse goodtables-ui to use this version and see how it looks.

**Comment by smth** [comment]
Hey. Nice.

On the stuff already mentioned:

- The rounded corners apply to the first child, so I think it's the multiple `tbody`s that's throwing that off.

- The protruding horizontal lines can be avoided by setting [this var](https://github.com/frictionlessdata/goodtables-ui/blob/master/src/styles.scss#L57) to equal the padding of the container. Those lines are pulled over by the amount set here.

- I agree that we are probably going to need a version with scrolling, but I was anticipating that being in a separate version of the table (maybe in a popup), hidden by default. The default version being truncated. The tables used in [this example](http://p.smth.uk/goodtables/ui/report/) are much wider than they appear. Unimportant columns have been hidden, signified by the ||.

Another thought, not specific to this implementation:

- We might want to think about what happens with missing / extra cells, as well as blank rows. I'm not sure it's as clear as it could be what's happening in that scenario. I wonder if we could add cells in but identify the unexpected number in another way.

**Comment by roll** [comment]
> I wouldn't display warnings as "buttons"

That was my improvisation) Hopefully there will a quick @smth run on stuff like this after goodtables.io integration. I think we also need a design to flash messages on the main site and a few other small things.

**Pull request merged**
